<template>
  <div class="px-5">
    <!-- Breadcrumbs -->
    <f-breadcrumbs :items="breadcrumbs"></f-breadcrumbs>

    <v-alert v-show="alert.show" type="success">{{alert.message}}</v-alert>

    <v-row>
       <v-col cols="12">
         <v-card outlined>
          <!-- Avatar Upload -->
          <v-form v-model="model.valid">
            <v-card-title>
              Basic Information
            </v-card-title>
            <v-card-subtitle class="text--secondary">
              Fill in the user information then click save to create a new user.
            </v-card-subtitle>

            <v-divider />

            <v-card-text>
              <v-container>
                <v-row>
                  <v-col md="2">
                    <v-avatar color="primary" size="80">
                      <v-img src="https://i.pravatar.cc/128"/>
                    </v-avatar>
                  </v-col>
                </v-row>
                <v-row>
                  <v-col cols="12" md="4">
                    <v-file-input
                      accept="image/*"
                      label="Upload Avatar"
                    ></v-file-input>
                  </v-col>
                </v-row>
                <v-row>
                  <v-col md="4">
                    <v-text-field
                      dense
                      v-model="model.first_name"
                      :rules="nameRules"
                      :counter="10"
                      label="First name"
                      required
                    ></v-text-field>
                  </v-col>

                  <v-col
                    cols="12"
                    md="4"
                  >
                    <v-text-field
                      dense
                      v-model="model.middle_name"
                      :rules="nameRules"
                      :counter="10"
                      label="Middle name"
                      required
                    ></v-text-field>
                  </v-col>

                  <v-col
                    cols="12"
                    md="4"
                  >
                    <v-text-field
                      dense
                      v-model="model.last_name"
                      :rules="nameRules"
                      :counter="10"
                      label="Last name"
                      required
                    ></v-text-field>
                  </v-col>

                  <v-col
                    cols="12"
                    md="4"
                  >
                    <v-text-field
                      dense
                      v-model="model.email"
                      :rules="emailRules"
                      label="E-mail"
                      required
                    ></v-text-field>
                  </v-col>

                  <v-col
                    cols="12"
                    md="4"
                  >
                    <v-text-field
                      dense
                      v-model="model.phone_number"
                      :rules="emailRules"
                      label="Phone Number"
                      persistent-hint
                      hint="Format: +63xxxxxxxxxx or 09xxxxxxxxx"
                      required
                    ></v-text-field>
                  </v-col>

                  <v-col md="4">
                    <v-select
                      v-model="model.sex"
                      dense
                      :items="options.sex"
                      item-text="text"
                      item-value="value"
                      label="Sex"
                      readonly
                    ></v-select>
                  </v-col>

                  <v-col md="4">
                    <v-text-field
                      dense
                      v-model="model.birthdate"
                      type="date"
                      :rules="emailRules"
                      label="Birthdate"
                      required
                    ></v-text-field>
                  </v-col>
                </v-row>
              </v-container>
            </v-card-text>

            <v-card-title>
              Credentials
            </v-card-title>
            <v-card-subtitle class="text--secondary">
              The username and password will be autogenerated as you type in the user's full name.
            </v-card-subtitle>

            <v-divider />

            <v-card-text>
              <v-container>
                <v-row>
                  <v-col
                    cols="12"
                    md="4"
                  >
                    <v-text-field
                      dense
                      v-model="model.username"
                      :rules="nameRules"
                      label="Username"
                      disabled
                      required
                    ></v-text-field>
                  </v-col>

                  <v-col
                    cols="12"
                    md="4"
                  >
                    <v-text-field
                      dense
                      v-model="model.password"
                      :rules="nameRules"
                      label="Password"
                      type="password"
                      disabled
                      required
                    ></v-text-field>
                  </v-col>
                </v-row>
              </v-container>
            </v-card-text>

            <v-card-title>
              Access Control
            </v-card-title>
            <v-card-subtitle class="text--secondary">
              Determine the type of user.
            </v-card-subtitle>
            <v-divider />

            <v-card-text>
              <v-list
                subheader
                three-line
                flat
              >
                <v-radio-group v-model="model.role">
                  <v-template v-for="(item, index) in roles" :key="index">

                    <v-divider
                      v-if="item.divider"
                      :key="index"
                      :inset="item.inset"
                    ></v-divider>

                    <v-list-item
                      v-else
                      :key="index"
                    >
                      <template #default>
                        <v-list-item-action>
                          <v-radio
                            :value="item.name"
                            color="primary"
                          ></v-radio>
                        </v-list-item-action>

                        <v-list-item-content>
                          <v-list-item-title>{{item.name}}</v-list-item-title>
                          <v-list-item-subtitle>
                            {{item.description}}
                          </v-list-item-subtitle>
                        </v-list-item-content>
                      </template>
                    </v-list-item>

                  </v-template>
                </v-radio-group>
              </v-list>
            </v-card-text>
          </v-form>

          <v-divider />

          <v-card-actions class="pa-4">
            <v-spacer/>
            <v-btn
              elevation="0"
              text
            >
              Reset
            </v-btn>
            <v-btn
              color="primary"
              elevation="0"
              @click="confirmDialog.show=!confirmDialog.show"
            >
              Save
            </v-btn>
          </v-card-actions>
        </v-card>
      </v-col>

      <!-- Confirm Dialog -->
      <v-dialog
        v-model="confirmDialog.show"
        persistent
        max-width="290"
      >
        <v-card>
          <v-card-title class="text-h5">
            Confirmation
          </v-card-title>
          <v-card-text>I am aware that this action is final and is irreversible.</v-card-text>
          <v-card-actions>
            <v-spacer></v-spacer>
            <v-btn
              text
              @click="confirmDialog.show = false"
            >
              Close
            </v-btn>
            <v-btn
              color="primary darken-1"
              @click="submit()"
              :loading="confirmDialog.loading"
            >
              Proceed
            </v-btn>
          </v-card-actions>
        </v-card>
      </v-dialog>
    </v-row>
  </div>
</template>

<script>
  export default {
    data: () => ({
      breadcrumbs: [{
        text: "Security",
        href: "/security"
      }, {
        text: "Users",
        href: "/security/users",
      }, {
        text: "John Doe",
        href: "/security/users/1",
      }, {
        text: "Update",
        disabled: true
      }],
      confirmDialog: {
        show: false,
        loading: false
      },
      alert: {
        message: null,
        show: false,
      },
      options: {
        sex: [{
          text: "Male",
          value: "male",
        }, {
          text: "Female",
          value: "female",
        }]
      },
      model: {
        id: 1,
        username: "jdelacruz",
        password: "password",
        first_name: "Juan",
        middle_name: "Reyes",
        last_name: "Dela Cruz",
        last_name: "Dela Cruz",
        email: "jdelacruz@mkphoenixmovers.com",
        sex: "male",
        phone_number: "09123445123",
        birthdate: "1990-09-09",
        role: "Admin",
      },
      roles: [
        {
          avatar: 'https://cdn.vuetifyjs.com/images/lists/1.jpg',
          name: 'Admin',
          description: `Has full access to all modules and functionalities.`,
        },
        { divider: true, inset: true },
        {
          avatar: 'https://cdn.vuetifyjs.com/images/lists/2.jpg',
          name: 'Driver',
          description: `Omnis aspernatur officia delectus blanditiis voluptatem nostrum quo nesciunt odio. Harum ut harum unde tempore ducimus eius distinctio. Incidunt aperiam accusamus dignissimos qui dolorum voluptatem et. Exercitationem sequi alias doloremque beatae voluptates illo non nihil ab. Velit qui corporis rerum reprehenderit..`,
        },
        { divider: true, inset: true },
        {
          avatar: 'https://cdn.vuetifyjs.com/images/lists/3.jpg',
          name: 'Developer',
          description: `Ea et ut voluptas aperiam molestiae non est. Ut blanditiis qui quas est nobis dignissimos ab aspernatur nulla. Consequatur nisi odit error facere distinctio. Similique non eaque quia et optio cum et odio quia. Vero nihil aut est qui. Aperiam nostrum dicta fugiat vero..`,
        },
      ]
    }),
    methods: {
      submit() {
        this.confirmDialog.loading = true
        setTimeout(() => {
          this.confirmDialog.loading = false
          this.confirmDialog.show = false
          this.alert.message = "User successfully updated!"
          this.alert.show = true
          this.$router.push({
            path: '/security/users/1',
            query: {
              alertMessage: this.alert.message,
              alertShow: this.alert.show,
            }
          })
        }, 1500)
      }
    }
  }
</script>
